### ISSUE TITLE
some problems 

### ISSUE THREAD

**Issue by antwal** [45-North-Ventures-LLC/jackpine#24]
hi 

i have tried but i have some problems 

build dist:
- if timber plugin is enabled theme not working 
- if i disable the timber plugin the theme working but with some problems

dev:
- yarn start working only browsersync on port 3001, the port 3000 not working

server start:
![image](https://user-images.githubusercontent.com/410736/103727012-7dfb0600-4fda-11eb-995c-a60fd7d0ff00.png)

browsersync working:
![image](https://user-images.githubusercontent.com/410736/103727056-9834e400-4fda-11eb-8ff1-e5c7dc608129.png)

external link is stucked:
![image](https://user-images.githubusercontent.com/410736/103727147-db8f5280-4fda-11eb-8944-1c584d63d178.png)

i use it inside a docker container

thanks.

**Comment by peterwhite** [comment]
Timber is part of Jackpine so you don't need the separate Timber plugin.

Does the local link (http://localhost:3000) display your site as expected? 

If not, could you:
- Check no other services (like Docker services, or Flywheel, WAMP, Valet etc) are running on port 3000
- Post your `docker-compose.yml` file
- Post your `wpackio.server.js` file 

I'll take a look and see if I can help!

**Comment by antwal** [comment]
> Timber is part of Jackpine so you don't need the separate Timber plugin.

OK, need disable it if use this theme

> Does the local link (http://localhost:3000) display your site as expected?

localhost or 172.16.86.4 is same host, the docker container run in "macvlan networks" with all ports open

but i have tried  a simple wget on localhost inside docker container but it not respond

> * Check no other services (like Docker services, or Flywheel, WAMP, Valet etc) are running on port 3000

yes ports are opened, in this container the ports are:
3000 -> wpack.io
3001 -> wpack.io - browsersync
9000 -> php 7.3

i have installed net-tools and curl for some test, all service working but the wpack.io on port 3000 not respond
![image](https://user-images.githubusercontent.com/410736/103764089-1f09b100-501b-11eb-83fd-fe8c4708a0a5.png)



> * Post your `docker-compose.yml` file

not use a docker-compose; i have any single containers for nginx, php (composer, nodejs, yarn), mysql, phpmyadmin, sftpserver with a dedicated ip address on network

> * Post your `wpackio.server.js` file

is your config, I have not made any changes

**Comment by peterwhite** [comment]
Are you sure port 8080 is serving WordPress and port 3000 is free for WPACK to hook to?

Otherwise I'm not sure - it looks like the problem is with WPACK.IO and your Docker setup, rather than with Jackpine. You might want to try asking this question [there](https://github.com/swashata/wp-webpack-script), somebody else might have fixed it.

You could also try elminating issues with your Docker setup by trying a separate Docker instance just for Jackpine - my docker-compose.yml is below:

```
version: '3.3'

services:
  db:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: x
      MYSQL_DATABASE: x
      MYSQL_USER: x
      MYSQL_PASSWORD: x
    ports:
       - "3308:3306"  
  wordpress:
    links:
      - db
    depends_on:
      - db
    image: wordpress:latest
    ports:
       - "8002:80"   
    restart: unless-stopped
    volumes:
      - ./wp-content:/var/www/html/wp-content
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: x
      WORDPRESS_DB_USER: x
      WORDPRESS_DB_PASSWORD: x
```
      
And my wpackio.server.js looks like this:
```
	host: undefined,
	// Your WordPress development server address
	// This is super important
	proxy: 'http://localhost:8002',
	// PORT on your localhost where you would want live server to hook
	port: 8003,
	// UI passed directly to browsersync
	ui: {
		port: 3001,
	},
	// Whether to show the "BrowserSync Connected"
	notify: false,
	// Open the local URL, set to false to disable
	open: false,
	// BrowserSync ghostMode, set to false to completely disable
	ghostMode: {
		clicks: true,
		scroll: true,
		forms: true,
	},
	// Override system calculated public path of the `dist` directory
	// This must have forward slash, otherwise it will not work.
	distPublicPath: undefined,
```
